[package]
name = "soft-ratatui-egui-modifiers-cosmic"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
color-eyre.workspace = true
eframe.workspace = true
itertools.workspace = true
palette.workspace = true
ratatui.workspace = true
embedded-graphics-unicodefonts.workspace = true
soft_ratatui = { path = "../..", default-features = false, features = ["cosmic-text"] }
