[package]
name = "soft-ratatui-egui-font-size-cycle"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
eframe.workspace = true
ratatui.workspace = true
soft_ratatui = { path = "../..", default-features = false, features = ["embedded-ttf"] }
