[package]
name = "soft-ratatui-bevy-demo"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
rand.workspace = true
ratatui.workspace = true
soft_ratatui = { path = "../..", features = ["bdf-parser"] }
