[package]
name = "soft-ratatui-bevy-parley-modifiers"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
itertools.workspace = true
ratatui.workspace = true
soft_ratatui = { path = "../..", default-features = false, features = ["parley-vello"] }
