[package]
name = "bevy_cube_example"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.0"
ratatui = { version = "0.29.0", default-features = false }
itertools = "0.14.0"
palette = "0.7.6"
color-eyre = "0.6.4"
soft_ratatui = { path = "../.." ,features=["bdf-parser"]}
embedded-graphics-unicodefonts = "0.2.0"
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
