[package]
name = "soft-ratatui-bevy-cube-colors"
edition = "2024"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
ratatui.workspace = true
itertools.workspace = true
palette.workspace = true
color-eyre.workspace = true
soft_ratatui = { path = "../..", features = ["bdf-parser"] }
embedded-graphics-unicodefonts.workspace = true
